apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app-backend
  template:
    metadata:
      labels:
        app: chat-app-backend
    spec:
      containers:
        - name: chat-app-backend
          image: myContainerRegistry.azurecr.io/chat-app-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/chat"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend
spec:
  selector:
    app: chat-app-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
